/**
 * Englische Entsprechungen der Prop-Schlagwörter.
 *
 * **Warum eine Tabelle und nicht zwei Listen am Prop.** Die Schlagwörter stehen
 * bei jedem der gut zweihundert Props in der Definition. Sie dort zu verdoppeln
 * hieße, jede Zeile anzufassen und danach zwei Listen parallel zu halten — die
 * laufen auseinander, genau wie zwei getrennte Wörterbücher es täten. Die
 * Schlagwörter sind stattdessen ein geschlossener Wortschatz: dreihundertzwanzig
 * Wörter, die sich einmal übersetzen lassen.
 *
 * Gesucht wird immer in *beiden* Sprachen, unabhängig davon, welche gerade
 * eingestellt ist. Wer auf Deutsch arbeitet und „chest" tippt, meint die Truhe.
 *
 * `tests/propTags.test.ts` prüft, dass kein Schlagwort ohne Eintrag bleibt —
 * dieselbe Zusage wie bei den Oberflächentexten.
 */

import { getLanguage } from '@/i18n';

/**
 * Deutsches Schlagwort → englische Wörter.
 *
 * Das erste Wort ist die Anzeige, die weiteren sind nur für die Suche da:
 * „kaputt" soll auch finden, wer „damaged" tippt.
 */
export const TAG_EN: Record<string, string[]> = {
  abtei: ['abbey'],
  acker: ['farmland', 'field'],
  alchemie: ['alchemy'],
  altar: ['altar'],
  amboss: ['anvil'],
  amphore: ['amphora'],
  anker: ['anchor'],
  anleger: ['jetty', 'dock'],
  auf: ['up'],
  aufstieg: ['ascent', 'stairs'],
  baerenfalle: ['bear trap'],
  band: ['ribbon', 'banner'],
  bank: ['bench'],
  banner: ['banner'],
  barde: ['bard'],
  bauernhof: ['farm'],
  baum: ['tree'],
  beere: ['berry'],
  berg: ['mountain'],
  bergwerk: ['mine'],
  beschriftung: ['label'],
  bett: ['bed'],
  beute: ['loot'],
  bibliothek: ['library'],
  biene: ['bee'],
  birke: ['birch'],
  blaetter: ['leaves'],
  blume: ['flower'],
  blut: ['blood'],
  boden: ['ground', 'floor'],
  bogen: ['bow', 'arch'],
  boot: ['boat'],
  brief: ['letter'],
  bruecke: ['bridge'],
  brunnen: ['well', 'fountain'],
  buch: ['book'],
  burg: ['castle'],
  busch: ['bush'],
  camp: ['camp'],
  deko: ['decoration'],
  dorf: ['village'],
  dorn: ['thorn'],
  duene: ['dune'],
  dungeon: ['dungeon'],
  edelstein: ['gem'],
  efeu: ['ivy'],
  ei: ['egg'],
  eingang: ['entrance'],
  eis: ['ice'],
  eisen: ['iron'],
  essen: ['food'],
  fackel: ['torch'],
  falle: ['trap'],
  falltuer: ['trapdoor'],
  farn: ['fern'],
  fass: ['barrel'],
  feld: ['field'],
  fels: ['boulder', 'rock'],
  fessel: ['shackle'],
  festung: ['fortress'],
  feuer: ['fire'],
  figur: ['figure'],
  fischer: ['fisherman'],
  fleck: ['stain', 'patch'],
  fluss: ['river'],
  folter: ['torture'],
  friedhof: ['graveyard'],
  frost: ['frost'],
  galgen: ['gallows'],
  garten: ['garden'],
  gasthaus: ['inn'],
  gebirge: ['mountains'],
  gedeck: ['tableware'],
  gefahr: ['danger'],
  gefangen: ['captive', 'prison'],
  geheim: ['secret'],
  gitter: ['grate', 'bars'],
  gletscher: ['glacier'],
  gold: ['gold'],
  grab: ['grave'],
  gras: ['grass'],
  grenze: ['border'],
  gross: ['large'],
  grube: ['pit'],
  hafen: ['harbour', 'port'],
  halle: ['hall'],
  handwerk: ['craft'],
  haufen: ['pile', 'heap'],
  haus: ['house'],
  hebel: ['lever'],
  heiligtum: ['shrine'],
  herbst: ['autumn', 'fall'],
  heu: ['hay'],
  hexe: ['witch'],
  hindernis: ['obstacle'],
  hocker: ['stool'],
  hoehle: ['cave'],
  hof: ['courtyard', 'yard'],
  holz: ['wood'],
  huegel: ['hill'],
  insel: ['island'],
  kaefig: ['cage'],
  kahl: ['bare'],
  kaktus: ['cactus'],
  kalt: ['cold'],
  kamin: ['fireplace'],
  kampf: ['combat'],
  kaputt: ['broken', 'damaged'],
  karren: ['cart'],
  karte: ['map'],
  kerker: ['jail', 'dungeon'],
  kerze: ['candle'],
  kessel: ['cauldron'],
  kette: ['chain'],
  kies: ['gravel'],
  kind: ['child'],
  kiste: ['crate'],
  kleider: ['clothes'],
  klein: ['small'],
  kletter: ['climbing'],
  kloster: ['monastery'],
  knochen: ['bone'],
  kochen: ['cooking'],
  koerper: ['body'],
  kompass: ['compass'],
  koralle: ['coral'],
  korb: ['basket'],
  kreis: ['circle'],
  kreuz: ['cross'],
  kreuzung: ['crossroads'],
  kristall: ['crystal'],
  krug: ['jug'],
  krypta: ['crypt'],
  kueche: ['kitchen'],
  kueste: ['coast'],
  kult: ['cult'],
  labor: ['laboratory'],
  lache: ['puddle'],
  lager: ['camp', 'storage'],
  lampe: ['lamp'],
  laterne: ['lantern'],
  laub: ['foliage', 'leaves'],
  laute: ['lute'],
  lava: ['lava'],
  leiche: ['corpse'],
  leine: ['rope', 'line'],
  leiter: ['ladder'],
  leucht: ['glowing'],
  leuchtturm: ['lighthouse'],
  licht: ['light'],
  liegend: ['fallen', 'lying'],
  loch: ['hole'],
  luke: ['hatch'],
  magie: ['magic'],
  markt: ['market'],
  maschine: ['machine'],
  massstab: ['scale bar'],
  mechanik: ['mechanism'],
  meer: ['sea'],
  mine: ['mine'],
  moebel: ['furniture'],
  moor: ['bog', 'moor'],
  moos: ['moss'],
  muehle: ['mill'],
  muenzen: ['coins'],
  muschel: ['shell'],
  musik: ['music'],
  nadel: ['conifer', 'needle'],
  nest: ['nest'],
  netz: ['net'],
  nord: ['north'],
  oase: ['oasis'],
  obelisk: ['obelisk'],
  offen: ['open'],
  ort: ['settlement', 'place'],
  palme: ['palm'],
  pass: ['pass'],
  pflanze: ['plant'],
  pflaster: ['pavement'],
  pflug: ['plough', 'plow'],
  pfuetze: ['puddle'],
  pilz: ['mushroom'],
  plan: ['plan'],
  platte: ['slab'],
  poller: ['bollard'],
  portal: ['portal'],
  pult: ['lectern', 'desk'],
  ranke: ['tendril'],
  ranken: ['vines'],
  rast: ['rest'],
  regal: ['shelf'],
  richtplatz: ['execution'],
  riese: ['giant'],
  riff: ['reef'],
  riss: ['crack'],
  ritual: ['ritual'],
  rolle: ['scroll'],
  ruestung: ['armour', 'armor'],
  ruine: ['ruin'],
  rund: ['round'],
  rune: ['rune'],
  sack: ['sack'],
  saeule: ['column', 'pillar'],
  sand: ['sand'],
  sanduhr: ['hourglass'],
  sarg: ['coffin'],
  schaden: ['damage'],
  schaedel: ['skull'],
  schale: ['bowl'],
  schalter: ['switch'],
  schatz: ['treasure'],
  scheit: ['log'],
  scheune: ['barn'],
  schiff: ['ship'],
  schild: ['shield', 'sign'],
  schilf: ['reeds'],
  schlacht: ['battle'],
  schlaf: ['sleep'],
  schlafsack: ['bedroll'],
  schleifen: ['grinding'],
  schmiede: ['forge', 'smithy'],
  schnee: ['snow'],
  scholle: ['floe'],
  schrank: ['cupboard'],
  schreiben: ['writing'],
  schutt: ['rubble'],
  schwert: ['sword'],
  see: ['lake'],
  seerose: ['water lily'],
  sitz: ['seat'],
  skala: ['scale'],
  skelett: ['skeleton'],
  speer: ['spear'],
  spiegel: ['mirror'],
  spiess: ['spike'],
  spinne: ['spider'],
  stadt: ['town', 'city'],
  staender: ['rack', 'stand'],
  stall: ['stable'],
  stamm: ['trunk'],
  stand: ['stall'],
  stapel: ['stack'],
  statue: ['statue'],
  stein: ['stone'],
  steinkreis: ['stone circle'],
  stollen: ['adit', 'tunnel'],
  strand: ['beach'],
  strasse: ['road', 'street'],
  strauch: ['shrub'],
  stroh: ['straw'],
  strudel: ['whirlpool'],
  struktur: ['structure'],
  studier: ['study'],
  stuhl: ['chair'],
  stumpf: ['stump'],
  sumpf: ['swamp'],
  tang: ['seaweed', 'kelp'],
  tanne: ['fir'],
  taverne: ['tavern'],
  teich: ['pond'],
  teller: ['plate'],
  tempel: ['temple'],
  teppich: ['carpet', 'rug'],
  thron: ['throne'],
  tier: ['animal'],
  tisch: ['table'],
  titel: ['title'],
  tod: ['death'],
  tonware: ['pottery'],
  tor: ['gate'],
  tot: ['dead'],
  trank: ['potion'],
  treibgut: ['driftwood'],
  treppe: ['stairs'],
  trog: ['trough'],
  truemmer: ['debris'],
  truhe: ['chest'],
  tuer: ['door'],
  turm: ['tower'],
  ufer: ['shore', 'bank'],
  uhr: ['clock'],
  umgefallen: ['toppled', 'fallen'],
  ungeheuer: ['monster'],
  verfallen: ['derelict'],
  verlies: ['dungeon'],
  vogel: ['bird'],
  vorrat: ['supplies'],
  vulkan: ['volcano'],
  wache: ['guard'],
  wachturm: ['watchtower'],
  waesche: ['laundry'],
  waffe: ['weapon'],
  wagen: ['wagon'],
  wald: ['forest'],
  wand: ['wall'],
  wappen: ['coat of arms'],
  wasser: ['water'],
  wasserfall: ['waterfall'],
  weg: ['path'],
  wegweiser: ['signpost'],
  weide: ['willow', 'pasture'],
  welle: ['wave'],
  welt: ['world'],
  wendel: ['spiral'],
  werkstatt: ['workshop'],
  wiege: ['cradle'],
  wiese: ['meadow'],
  wind: ['wind'],
  windrose: ['compass rose'],
  winter: ['winter'],
  wissen: ['knowledge'],
  wohnen: ['living'],
  wrack: ['wreck'],
  wueste: ['desert'],
  wurzel: ['root'],
  zahnrad: ['gear', 'cog'],
  zaun: ['fence'],
  zeit: ['time'],
  zelle: ['cell'],
  zelt: ['tent'],
};

/**
 * Alle Wörter, unter denen ein Schlagwort zu finden sein soll.
 *
 * Ein unbekanntes Schlagwort — etwa von einem importierten Asset — bleibt wie
 * es ist. Es zu verschlucken wäre schlimmer, als es unübersetzt zu zeigen.
 */
export function tagWords(tag: string): string[] {
  const en = TAG_EN[tag];
  return en ? [tag, ...en] : [tag];
}

/** Anzeige eines Schlagworts in der eingestellten Sprache. */
export function tagLabel(tag: string): string {
  if (getLanguage() === 'de') return tag;
  return TAG_EN[tag]?.[0] ?? tag;
}
